name: "Deploy Onboardly to Google Cloud Run"
'on':
  push:
    branches:
      - master
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: onboardly
  RUN_REGION: europe-west1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  EMAIL: ${{ secrets.GCP_EMAIL }}
  SERVICE_ID: ${{ secrets.GCP_SERVICE_ID }}
jobs:
  deploy:
    name: "Deploying Onboardly"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy now')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 286.0.0
          service_account_key: '${{ secrets.GCP_SA_KEY_JSON }}'
          service_account_email: $EMAIL
          project_id: $PROJECT_ID
      - name: "Building"
        run: |-
          gcloud builds submit \
            --tag gcr.io/$PROJECT_ID/$SERVICE_ID
      - name: "Deploy"
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: $SERVICE_ID
          image: gcr.io/$PROJECT_ID/$SERVICE_ID
          region: REGION
          credentials: '${{ secrets.GCP_SA_KEY_JSON }}'
          project_id: $PROJECT_ID
