name: "Deploy Onboardly to Google Cloud Run"
'on':
  push:
    branches:
      - master
env:
  PROJECT_ID: onboardly-380704
  RUN_REGION: europe-west1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  EMAIL: ${{ secrets.GCP_EMAIL }}
  SERVICE_ID: onboardly
jobs:
  deploy:
    name: "Deploying Onboardly"
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy now')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '318.0.0'
          service_account_email: $EMAIL
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: "Setting up"
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '318.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: $EMAIL
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: "Building"
        run: |-
          gcloud builds submit \
            --tag gcr.io/onboardly-380704/onboardly

      - name: "Deploy"
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: $SERVICE_ID
          image: gcr.io/$PROJECT_ID/$SERVICE_ID
          region: REGION
          credentials: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: $PROJECT_ID
